DETS_TXT: /MS3D/tools/cfgs/target_nuscenes/label_generation/round2/cfgs/ensemble_detections.txt
SAVE_DIR: /MS3D/tools/cfgs/target_nuscenes/label_generation/round2/ps_labels
DATA_CONFIG_PATH: /MS3D/tools/cfgs/dataset_configs/nuscenes_dataset_da.yaml

PS_SCORE_TH: # veh,ped,cyc
  POS_TH: [0.7,0.7,0.5]
  NEG_TH: [0.2,0.15,0.1]

ENSEMBLE_KBF:
  DISCARD: [1, 1, 1]
  RADIUS: [1.5, 0.3, 0.2]
  NMS: [0.1, 0.3, 0.1]

TRACKING:
  VEH_ALL:
    RUNNING:
        SCORE_TH: 0.5
        MAX_AGE_SINCE_UPDATE: 2
        MIN_HITS_TO_BIRTH: 2
        ASSO: giou
        ASSO_TH: 1.3
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: -0.3
  VEH_STATIC:
    RUNNING:
        SCORE_TH: 0.3
        MAX_AGE_SINCE_UPDATE: 3
        MIN_HITS_TO_BIRTH: 2
        ASSO: iou_2d
        ASSO_TH: 0.7
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: 0.5
  PEDESTRIAN:
    RUNNING:
        SCORE_TH: 0.2
        MAX_AGE_SINCE_UPDATE: 2
        MIN_HITS_TO_BIRTH: 2
        ASSO: giou
        ASSO_TH: 1.5
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: -0.5

TEMPORAL_REFINEMENT:
  TRACK_FILTERING:
    MIN_NUM_STATIC_VEH_TRACKS: 8
    MIN_NUM_PED_TRACKS: 7  
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_VEH_ALL: 4
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_VEH_STATIC: 2
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_PED: 1
    USE_STATIC_PED_TRACKS: false
  ROLLING_KBF:
    MIN_STATIC_SCORE: 0.8
    ROLLING_KDE_WINDOW: 40
  PROPAGATE_BOXES:
    MIN_STATIC_TRACKS: 10
    N_EXTRA_FRAMES: 40
    DEGRADE_FACTOR: 0.99
    MIN_SCORE_CLIP: 0.3
